version: '3.8'

services:
  db:
    image: postgres:14.6-alpine
    restart: always
    environment:
      - POSTGRES_DB=biblioteca_ubec
      - POSTGRES_USER=biblioteca_ubec
      - POSTGRES_PASSWORD=biblioteca_ubec
      - TZ=America/Araguaina
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data
volumes:
  db:
    driver: local
