-- liquibase formatted sql
-- changeset JLPimenta:20230411-1-add.pessoa

CREATE TABLE pessoa
(
    ID_PESSOA        VARCHAR(36)  NOT NULL,
    NOME             VARCHAR(100) NOT NULL,
    CPF              VARCHAR(11)  NOT NULL,
    EMAIL            VARCHAR(100) NOT NULL,
    TELEFONE         VARCHAR(11),
    ID_ENDERECO      VARCHAR(36),
    DATA_NASCIMENTO  DATE,
    SEXO             VARCHAR(20),
    SITUACAO         BOOLEAN      NOT NULL,
    DATA_CRIACAO     TIMESTAMP    NOT NULL,
    DATA_ATUALIZACAO TIMESTAMP,

    CONSTRAINT PK_PESSOA PRIMARY KEY (ID_PESSOA),
    CONSTRAINT FK_PESSOA_ENDERECO FOREIGN KEY (ID_ENDERECO) REFERENCES endereco (ID_ENDERECO)
);